### ISSUE TITLE
importing plugins fails

### ISSUE THREAD

**Issue by sancelot** [vanderschaarlab/synthcity#262]
## Description
it installs from pip, but fails when running example

## How to Reproduce

importing plugins fails

Traceback (most recent call last):
  File "C:\Users\sancelot\OneDrive - NUMALLIANCE\Documents\WORKSPACE\sinthcity\test.py", line 1, in <module>
    from synthcity.plugins import Plugins
  File "c:\Users\sancelot\OneDrive - NUMALLIANCE\Documents\WORKSPACE\sinthcity\.venv\Lib\site-packages\synthcity\plugins\__init__.py", line 9, in <module>   
    from synthcity.plugins.core.plugin import Plugin, PluginLoader  # noqa: F401,E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sancelot\OneDrive - NUMALLIANCE\Documents\WORKSPACE\sinthcity\.venv\Lib\site-packages\synthcity\plugins\core\plugin.py", line 16, in <module>
    from synthcity.metrics.plots import plot_marginal_comparison, plot_tsne
  File "c:\Users\sancelot\OneDrive - NUMALLIANCE\Documents\WORKSPACE\sinthcity\.venv\Lib\site-packages\synthcity\metrics\__init__.py", line 2, in <module>   
    from .eval import Metrics  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sancelot\OneDrive - NUMALLIANCE\Documents\WORKSPACE\sinthcity\.venv\Lib\site-packages\synthcity\metrics\eval.py", line 17, in <module>      
    from .eval_detection import (
  File "c:\Users\sancelot\OneDrive - NUMALLIANCE\Documents\WORKSPACE\sinthcity\.venv\Lib\site-packages\synthcity\metrics\eval_detection.py", line 20, in <module>
    from synthcity.plugins.core.models.convnet import suggest_image_classifier_arch
  File "c:\Users\sancelot\OneDrive - NUMALLIANCE\Documents\WORKSPACE\sinthcity\.venv\Lib\site-packages\synthcity\plugins\core\models\convnet.py", line 7, in 
<module>
    from monai.networks.layers.factories import Act
  File "c:\Users\sancelot\OneDrive - NUMALLIANCE\Documents\WORKSPACE\sinthcity\.venv\Lib\site-packages\monai\__init__.py", line 58, in <module>
    load_submodules(sys.modules[__name__], False, exclude_pattern=excludes)
  File "c:\Users\sancelot\OneDrive - NUMALLIANCE\Documents\WORKSPACE\sinthcity\.venv\Lib\site-packages\monai\utils\module.py", line 212, in load_submodules  
    importer.find_module(name).load_module(name)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FileFinder' object has no attribute 'find_module'## Expected Behavior

## System Information
 - OS: windows 
 - OS Version: [e.g. 22]
 - Language Version: python 3.12.2
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome]
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by Feinster** [comment]
I have the same error, any workarounds?

**Comment by robsdavis** [comment]
Hi @sancelot and @Feinster,

This looks like a python version issue. Currently we are only testing synthcity against python version 3.8. 3.9, and 3.10. We will update to include newer versions soon, but in the meantime you should receive good results with python 3.8-10. Please reply if this does not resolve your issue and I will re-open this issue
